# Algorithme classique du problème du sac à dos

In [1009]:
import numpy as np

# Classique

In [1010]:
weights = np.array([10, 20, 30, 40, 50])
values = np.array([60, 100, 120, 140, 160])
max_weight = np.sum(weights) // 3

population_size = 100

population = np.random.randint(2, size=(population_size, weights.shape[0]))
print(population)

[[0 1 0 0 0]
 [1 1 0 0 1]
 [1 0 1 1 1]
 [0 1 0 1 1]
 [0 1 0 1 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 1 0 1 1]
 [0 1 0 0 0]
 [1 0 1 0 1]
 [0 0 0 1 1]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [1 0 1 0 0]
 [0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 0 0 0 1]
 [1 1 1 1 0]
 [0 0 1 1 0]
 [1 0 1 0 1]
 [0 0 1 1 0]
 [0 0 0 1 0]
 [1 1 0 0 0]
 [1 0 0 0 1]
 [1 1 0 1 1]
 [0 0 1 0 0]
 [1 0 0 1 1]
 [1 1 0 1 1]
 [0 1 0 0 0]
 [1 1 0 1 0]
 [1 0 1 0 0]
 [0 0 0 0 0]
 [0 1 1 0 0]
 [1 0 1 1 0]
 [1 0 1 0 1]
 [0 0 0 0 0]
 [1 1 1 0 1]
 [0 1 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 1]
 [1 0 0 0 1]
 [0 1 1 1 0]
 [1 1 1 1 1]
 [0 0 1 1 0]
 [0 0 0 0 1]
 [1 1 0 0 0]
 [0 1 0 1 1]
 [1 0 1 1 1]
 [0 1 0 1 0]
 [1 0 0 0 0]
 [0 0 1 1 0]
 [1 0 0 0 1]
 [0 0 1 1 1]
 [0 1 0 1 1]
 [1 0 0 0 1]
 [0 0 0 0 1]
 [0 1 0 1 1]
 [0 1 0 0 0]
 [1 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 1 0]
 [1 0 1 0 0]
 [0 0 0 1 1]
 [1 0 1 1 0]
 [0 1 1 0 1]
 [0 1 0 0 1]
 [0 0 1 0 0]
 [0 0 0 1 1]

In [1011]:
def fitness(weight, value, population, max_weight):
    arg_fitness = np.empty(population.shape[0])
    for i in range(population.shape[0]):
        S1 = np.sum(population[i] * value)
        S2 = np.sum(population[i] * weight)
        if S2 > max_weight:
            arg_fitness[i] = 0
        else:
            arg_fitness[i] = S1
    return arg_fitness

In [1012]:
fitness(weights, values, population, max_weight)

array([100.,   0.,   0.,   0.,   0., 140.,   0.,   0., 100.,   0.,   0.,
         0.,   0.,   0.,   0., 180., 160., 220., 140.,   0.,   0., 160.,
       160.,   0.,   0., 160.,   0.,   0.,   0.,   0., 140., 160.,   0.,
         0., 120.,   0.,   0., 100.,   0., 180.,   0., 220.,   0.,   0.,
         0.,   0., 220., 100.,   0.,   0.,   0.,   0.,   0., 160., 160.,
         0.,   0.,   0.,  60.,   0.,   0.,   0.,   0.,   0., 160.,   0.,
       100., 180.,  60., 200., 180.,   0.,   0.,   0.,   0., 120.,   0.,
       200., 120., 180.,   0., 220., 180.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0., 100., 200.,   0.,   0.,   0.,   0.,   0., 140.,
         0.])

In [1013]:
def selection_roulette(fitness, population):
    # Selectionner par la roulette les 2 meilleurs individus, ils doivent être différents
    parents = []
    somme = np.sum(fitness)
    fitness_roulette = fitness / somme
    for i in range(2):
        # Tirage aléatoire entre 0 et 1
        tirage = np.random.rand()
        # On cherche l'indice de l'individu qui correspond au tirage et on le stocke dans parents puis on le supprime de la population
        somme = 0
        for j in range(fitness_roulette.shape[0]):
            somme += fitness_roulette[j]
            if somme >= tirage:
                parents.append(population[j])
                population = np.delete(population, j, axis=0)
                fitness = np.delete(fitness, j, axis=0)
                fitness_roulette = np.delete(fitness_roulette, j, axis=0)
                break
    return parents
    

In [1014]:
print(selection_roulette(fitness(weights, values, population, max_weight), population))

[array([0, 1, 1, 0, 0]), array([1, 0, 1, 0, 0])]


In [1015]:
def crossover(parents):
    # On choisit un point de croisement aléatoire
    point_croisement = np.random.randint(1, parents[0].shape[0])
    # On crée les enfants
    enfant1 = np.concatenate((parents[0][:point_croisement], parents[1][point_croisement:]))
    enfant2 = np.concatenate((parents[1][:point_croisement], parents[0][point_croisement:]))
    return enfant1, enfant2

In [1016]:
print(crossover(selection_roulette(fitness(weights, values, population, max_weight), population)))

(array([0, 1, 1, 0, 0]), array([1, 0, 1, 0, 0]))


In [1017]:
def mutation(enfants):
    # On choisit un point de mutation aléatoire
    point_mutation = np.random.randint(0, enfants[0].shape[0])
    # On crée les enfants si le point de mutation est 0 on le change en 1 et inversement
    if enfants[0][point_mutation] == 0:
        enfants[0][point_mutation] = 1
    else:
        enfants[0][point_mutation] = 0
    return enfants

In [1018]:
print(mutation(crossover(selection_roulette(fitness(weights, values, population, max_weight), population))))

(array([0, 1, 0, 0, 0]), array([0, 1, 0, 0, 0]))


In [1019]:
def evolution(arg_population, arg_fitness, arg_max_weight, mutation_rate=0.1):
    # On sélectionne les parents
    parents = selection_roulette(arg_fitness, arg_population)
    # On crée les enfants
    enfants = crossover(parents)
    # On mute les enfants avec une probabilité
    if np.random.rand() < mutation_rate:
        enfants = mutation(enfants)
    # On ajoute les enfants à la population si ils améliorent le pire individu
    enfants = np.array(enfants)
    fitness_enfants = fitness(weights, values, enfants, arg_max_weight)
    fitness_population = fitness(weights, values, arg_population, arg_max_weight)
    for i in range(2):
        if fitness_enfants[i] > np.min(fitness_population):
            # On remplace le pire individu par l'enfant
            arg_population[np.argmin(fitness_population)] = enfants[i]
            fitness_population[np.argmin(fitness_population)] = fitness_enfants[i]
    # On calcule la fitness de la nouvelle population
    arg_fitness = fitness_population
    return arg_population

In [1020]:
print(evolution(population, fitness(weights, values, population, max_weight), max_weight))

[[0 1 0 0 0]
 [1 0 1 0 0]
 [1 0 1 1 1]
 [0 1 0 1 1]
 [0 1 0 1 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 1 0 1 1]
 [0 1 0 0 0]
 [1 0 1 0 1]
 [0 0 0 1 1]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [1 0 1 0 0]
 [0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 0 0 0 1]
 [1 1 1 1 0]
 [0 0 1 1 0]
 [1 0 1 0 1]
 [0 0 1 1 0]
 [0 0 0 1 0]
 [1 1 0 0 0]
 [1 0 0 0 1]
 [1 1 0 1 1]
 [0 0 1 0 0]
 [1 0 0 1 1]
 [1 1 0 1 1]
 [0 1 0 0 0]
 [1 1 0 1 0]
 [1 0 1 0 0]
 [0 0 0 0 0]
 [0 1 1 0 0]
 [1 0 1 1 0]
 [1 0 1 0 1]
 [0 0 0 0 0]
 [1 1 1 0 1]
 [0 1 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 1]
 [1 0 0 0 1]
 [0 1 1 1 0]
 [1 1 1 1 1]
 [0 0 1 1 0]
 [0 0 0 0 1]
 [1 1 0 0 0]
 [0 1 0 1 1]
 [1 0 1 1 1]
 [0 1 0 1 0]
 [1 0 0 0 0]
 [0 0 1 1 0]
 [1 0 0 0 1]
 [0 0 1 1 1]
 [0 1 0 1 1]
 [1 0 0 0 1]
 [0 0 0 0 1]
 [0 1 0 1 1]
 [0 1 0 0 0]
 [1 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 1 0]
 [1 0 1 0 0]
 [0 0 0 1 1]
 [1 0 1 1 0]
 [0 1 1 0 1]
 [0 1 0 0 1]
 [0 0 1 0 0]
 [0 0 0 1 1]

In [1021]:
def algo_genetique(population_finale, arg_weights, arg_values, arg_max_weight, nb_iterations=1000):
    # On trie la population finale par ordre décroissant de fitness
    population_finale = population_finale[np.argsort(fitness(arg_weights, arg_values, population_finale, arg_max_weight))[::-1]]
    # On retourne le meilleur individu
    return population_finale[0], fitness(arg_weights, arg_values, population_finale, arg_max_weight)[0]

In [1022]:
algo_genetique(population, weights, values, max_weight)

(array([0, 1, 1, 0, 0]), 220.0)

# Les 5 jeux de données

## Jeu de données 1

In [1023]:
weights_1 = np.array([10, 20, 30, 40, 50])
values_1 = np.array([60, 100, 120, 140, 160])
max_weight_1 = np.sum(weights) // 3

## Jeu de données 2

In [1024]:
weights_2 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
values_2 = np.array([60, 100, 120, 140, 160, 180, 200, 220, 240, 260])
max_weight_2 = np.sum(weights) // 3

## Jeu de données 3

In [1025]:
weights_3 = [83, 73, 22, 1, 65, 98, 64, 40, 92, 68, 6, 39, 90, 73, 7, 99, 6, 52, 23, 14]
values_3 = [8, 17, 2, 17, 20, 16, 15, 2, 19, 10, 19, 6, 19, 5, 16, 21, 19, 18, 9, 1]
max_weight_3 = np.sum(weights) // 3

# Quantique 

In [1026]:
weights_q = np.array([10, 20])
values_q = np.array([60, 100])
max_weight_q = np.sum(weights_q) // 3

In [1027]:
def initialiser_q(n, m):
    Q = []
    un_ele = [1/(2**0.5) for i in range(m)]
    for i in range(n):
        Q.append([un_ele, un_ele])
    return Q

In [1028]:
print(initialiser_q(5, 2))

[[[0.7071067811865475, 0.7071067811865475], [0.7071067811865475, 0.7071067811865475]], [[0.7071067811865475, 0.7071067811865475], [0.7071067811865475, 0.7071067811865475]], [[0.7071067811865475, 0.7071067811865475], [0.7071067811865475, 0.7071067811865475]], [[0.7071067811865475, 0.7071067811865475], [0.7071067811865475, 0.7071067811865475]], [[0.7071067811865475, 0.7071067811865475], [0.7071067811865475, 0.7071067811865475]]]


In [1029]:
def initialiser_p(n, m, Q):
    P = []
    for i in range(n):
        aux = []
        for j in range(m):
            r = np.random.rand()
            if r < Q[i][0][j]**2:
                aux.append(0)
            else:
                aux.append(1)
        P.append(aux)
    return P

In [1030]:
print(initialiser_p(5, 2, initialiser_q(5, 2)))

[[0, 1], [1, 0], [1, 0], [1, 0], [0, 0]]


In [1031]:
def evaluer_fitness(P, arg_weights, arg_values, arg_max_weight):
    tab_fitness = []
    for i in range(len(P)):
        S1 = np.sum(P[i] * arg_values)
        S2 = np.sum(P[i] * arg_weights)
        if S2 > arg_max_weight:
            tab_fitness.append(0)
        else:
            tab_fitness.append(S1)
    return tab_fitness

In [1032]:
print(evaluer_fitness(initialiser_p(5, 2, initialiser_q(5, 2)), weights_q, values_q, max_weight_q))

[0, 60, 0, 0, 0]


In [1033]:
def recuperer_meilleur(P, arg_fitness):
    return P[np.argmax(arg_fitness)], np.max(arg_fitness)

In [1034]:
sol = initialiser_p(5, 2, initialiser_q(5, 2))

print(recuperer_meilleur(sol, evaluer_fitness(sol, weights_q, values_q, max_weight_q)))

([1, 0], 60)


In [1035]:
import random as r

def calcule_alpha_beta(alpha, beta, gamma):
    alpha_prime = alpha * np.cos(gamma) - beta * np.sin(gamma)
    beta_prime = alpha * np.sin(gamma) + beta * np.cos(gamma)
    return alpha_prime, beta_prime

print(calcule_alpha_beta(0.5, 0.5, np.random.rand() * np.pi))

def update(Q):
    for i in range(len(Q)):
        for j in range(len(Q[i])):
            alpha = Q[i][0][j]
            beta = Q[i][1][j]
            gamma = r.random() * np.pi
            alpha_prime, beta_prime = calcule_alpha_beta(alpha, beta, gamma)
            Q[i][0][j] = alpha_prime
            Q[i][1][j] = beta_prime
    return Q

(-0.5772035741693046, 0.40845566952385437)


In [1036]:
print(update(initialiser_q(5, 2)))

[[[-1.0127099091680691, 0.2652309535462921], [-1.0127099091680691, 0.2652309535462921]], [[-1.0127099091680691, 0.2652309535462921], [-1.0127099091680691, 0.2652309535462921]], [[-1.0127099091680691, 0.2652309535462921], [-1.0127099091680691, 0.2652309535462921]], [[-1.0127099091680691, 0.2652309535462921], [-1.0127099091680691, 0.2652309535462921]], [[-1.0127099091680691, 0.2652309535462921], [-1.0127099091680691, 0.2652309535462921]]]


In [1037]:
# Créer 𝑃(𝑡) en observant 𝑄(𝑡) et évaluer 𝑃(𝑡) : Sur la base de l'observation de 𝑄(𝑡), les solutions binaires 𝑃(𝑡) sont formées  

def creer_p(Q):
    P = []
    for i in range(len(Q)):
        aux = []
        for j in range(len(Q[i][1])):
            r = np.random.rand()
            if r < Q[i][0][j]**2:
                aux.append(0)
            else:
                aux.append(1)
        P.append(aux)
    return P

In [1038]:
print(creer_p(initialiser_q(5, 2)))

[[1, 0], [1, 1], [0, 1], [0, 0], [1, 0]]


In [1039]:
# Algorithme quantique

def algorithme_quantique(n, m, arg_weights, arg_values, arg_max_weight, nb_iterations):
    Q = initialiser_q(n, m)
    B = []
    for i in range(nb_iterations):
        Q = update(Q)
        P = creer_p(Q)
        fct_fitness = evaluer_fitness(P, arg_weights, arg_values, arg_max_weight)
        P, fct_fitness = recuperer_meilleur(P, fct_fitness)
        B.append([P, fct_fitness])
    return B

In [1040]:
print(algorithme_quantique(5, 2, weights_q, values_q, max_weight_q, 10))

[[[1, 1], 0], [[1, 1], 0], [[1, 1], 0], [[1, 1], 0], [[1, 1], 0], [[1, 1], 0], [[1, 1], 0], [[1, 1], 0], [[1, 1], 0], [[1, 1], 0]]


In [1041]:
print(algorithme_quantique(100, len(weights_1), weights_1, values_1, max_weight_1, 1000))

[[[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0], 160], [[1, 1, 0, 0, 0

In [1042]:
def get_best(B):
    meilleur_element = max(B, key=lambda x: x[1])
    return meilleur_element

In [1043]:
print(get_best(algorithme_quantique(100, len(weights_1), weights_1, values_1, max_weight_1, 1000)))

[[1, 1, 0, 0, 0], 160]


In [1044]:
population_gene = np.random.randint(2, size=(100, weights_1.shape[0]))

print(algo_genetique(population_gene, weights_1, values_1, max_weight_1, 1000))

(array([0, 1, 1, 0, 0]), 220.0)
